"""Apply the reviewed SSS patches (accuracy corrections + 3 new questions)
to en/de/ru/fa locales, mirroring the TR updates from this session."""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
MSG = ROOT / "messages"

# ---------------------------------------------------------------------------
# PATCHES per locale — each entry: (cat_idx, item_idx, question_or_None, answer)
# New items are appended separately.
# ---------------------------------------------------------------------------

EN_PATCHES = [
    (0, 0, None,
     "Northern Cyprus has been one of the most dynamic Mediterranean property markets of the last several years. Since 2020, prices in coastal resort areas have risen notably, with annual appreciation varying roughly between 10% and 25% depending on location and project (no single figure — it depends heavily on the micro-market). Key advantages include low entry prices, sterling-denominated pricing, 300+ sunny days per year, widespread use of English, direct flights to Turkey, a growing tourism sector and constant rental demand from 20+ universities. Past performance, however, does not guarantee future returns; independent due diligence and legal advice are essential before investing."),
    (0, 1, None,
     "Per-m² prices in Northern Cyprus are generally well below the tourist areas of Spain, Southern Cyprus, Greece and Italy. For example, a beachfront 1+1 apartment in Iskele's Long Beach area currently trades roughly at 70,000-130,000 GBP, while a comparable property in Southern Cyprus (Ayia Napa / Larnaca) sits at 180,000+ EUR and in Costa del Sol at 200,000+ EUR. Prices vary by project, delivery status, view and land share — check our current listings for up-to-date numbers."),
    (0, 4, None,
     "Short-term rental income in Northern Cyprus is seasonal. During high season (June-September) in Iskele Long Beach and Kyrenia, typical daily rates are: 1+1 apartments 50-100 GBP, 2+1 apartments 80-160 GBP, villas 150-400 GBP. Off-season rates drop notably. Annual occupancy with professional management and good location ranges 60-85%. A short-term rental licence from the municipality, VAT registration and annual income tax declarations are expected — the legal and tax framework differs from long-term leasing."),

    (4, 0, None,
     "There are four main types of title deed in Northern Cyprus: "
     "1) Pre-1974 Turkish Title (Türk Malı Koçan) — properties owned by Turkish Cypriots before 1974. Legally the strongest and typically the most valuable. "
     "2) Equivalent Title (Eşdeğer) — given to Turkish Cypriots displaced from the south in exchange for the property they left behind, on an equivalent-value point system. State-backed and common in the market. "
     "3) Allocated Title (Tahsis / TMD) — allocated by the state after 1974 to arrivals from Turkey. Its international legal status can be contentious and is generally not recommended for foreign buyers. "
     "4) Foreign Title / Post-transfer Title — titles that have been transferred to foreign nationals (via Council of Ministers consent); a new foreign buyer must go through the consent process again. "
     "Always commission an independent solicitor's title search before purchase and evaluate the risk profile of the title type."),
    (4, 1, None,
     "For Turkish citizens, who do not require Council of Ministers consent, title transfer usually completes within a few days to 1-2 weeks once documents are in order. For foreign buyers the process is different: under the Immovable Property Acquisition and Long Term Lease (Foreigners) Law, the application goes to the Ministry of Interior, passes through police and military security vetting, and then receives Council of Ministers approval. After the 2023 amendments the average timeline is 6-12 months and can be longer during busy periods. During this interval the sales contract must be registered at the Land Registry (Specific Performance) to protect the buyer."),
    (4, 2, None,
     "Yes — absolutely, and for foreign buyers this is the single most critical legal step in Northern Cyprus. Registering the sales contract at the Land Registry within 21 days (after paying the contract stamp duty) gives the buyer 'Specific Performance' protection under the Contracts Law: the seller cannot resell the property, cannot place a mortgage or lien on it, and cannot walk away from the contract in favour of another buyer. A buyer who fails to register the contract risks losing all rights until title transfer completes. Stamp duty is approximately 0.5% of the contract price; registration fees have a fixed and a value-based component."),
    (4, 4, None,
     "Yes — if you live abroad you can authorise your lawyer via an apostilled (Hague Convention) or a TRNC-consulate-certified power of attorney. PoAs issued by Turkish notaries are valid in the TRNC; those from other countries must be apostilled (or TRNC consulate certified). The PoA must list the authorised acts explicitly: title transfer, Council of Ministers application, opening a bank account, signing contracts at the notary, and so on. A limited PoA covering only the required acts is preferred over an unlimited general PoA. Total cost including translation is typically 100-300 GBP."),

    (5, 0, None,
     "Yes — foreign natural persons may acquire real estate in Northern Cyprus with Council of Ministers consent. The governing legislation is the Immovable Property Acquisition and Long Term Lease (Foreigners) Law (No. 52/2008 and subsequent amendments). Current rules include provisions that let a foreign individual acquire more than one property, with combined area and number of units limited by law. Because these limits have been amended over time (most recently in 2023), we strongly recommend confirming in writing the exact limits in force on the day of purchase with your solicitor and with us. Turkish citizens are not subject to this consent procedure (see the following question)."),
    (5, 1, None,
     "Council of Ministers consent is the official approval required for a foreign national to acquire property in the TRNC. The application, filed with the Ministry of Interior, typically requires: passport copy, proof of address, criminal record certificate (apostilled from country of origin), passport photos, a copy of the sales contract, title deed and search report, and the application forms. Flow: application → police and military security vetting → Council of Ministers decision → title transfer on approval. Average timeline after 2023 is 6-12 months. Registering the sales contract at the Land Registry (Specific Performance) during this period is essential. Your solicitor prepares and follows the application."),
    (5, 2, None,
     "Yes — there are important exemptions for Turkish nationals. TC citizens are not subject to the Council of Ministers consent procedure: title is transferred directly at the Land Registry and can complete within a few days. Transactions are processed with a TC ID card or passport. The property-count and land-area limits that apply to foreigners are not imposed on TC citizens in the same way. This gives TC nationals a material advantage in terms of process, timing and legal procedure."),
    (5, 4, None,
     "Yes — it is possible to incorporate a TRNC-registered limited company (Ltd.) and acquire property through it, which in certain cases lets investors exceed the limits that apply to foreign natural persons. Incorporation takes around 2-4 weeks; total cost (legal fees, registration, share capital) is typically 2,000-4,000 GBP. Be aware of the ongoing costs and obligations: corporate tax on profit from resale, VAT treatment nuances, annual audit, accountant fees, and rental-income reporting. Companies are effective for multi-property portfolios; for a single property, acquiring as a natural person is usually more cost-effective. Model the total cost with a tax advisor before deciding."),

    (6, 0, None,
     "Yes — foreign property owners in the TRNC may apply for a 'temporary residence permit'. Applications are submitted to the Ministry of Interior / Immigration Department with: passport and copies, title deed or sales contract, TRNC medical check report, criminal record certificate, two passport photos, proof of sufficient income or bank balance, and the application fees. Temporary residence is typically granted for 1 year and is renewable while conditions are met. Because criteria change from year to year, please confirm current requirements with the Immigration Department or your solicitor before applying."),
    (6, 2, None,
     "TRNC citizenship is possible under specific conditions, but property ownership does not automatically grant it. Main routes: 1) Marriage — a minimum legal residence period as a spouse of a TRNC citizen before applying, 2) Long-term residence — continuous lawful residence over the years prescribed by law, demonstrating ties to the country, 3) Exceptional grounds — special service or investment. The process is complex and shaped by laws that have been amended over the years — current waiting periods, language/culture assessments and other criteria change over time. Before applying, obtain a written opinion on the current regime from a solicitor specialised in immigration law."),

    (7, 0, None,
     "The Northern Cyprus property market has grown significantly in recent years, particularly in coastal resort zones — but past performance is not a guarantee of future returns. A reasonable long-term rental yield (net, after costs) sits around 4-8% annually; short-term / holiday lets with professional management can reach 6-12%. Annual appreciation varies greatly by year and location. Typical patterns: near universities — steady rental demand and moderate appreciation; coastal tourism (Long Beach, Bafra, Esentepe) — higher Airbnb returns but high seasonal volatility; central Kyrenia — established demand and stable long-term tenants. Independent due diligence and cash-flow modelling are essential before every investment."),
    (7, 2, None,
     "Mortgage options in the TRNC are limited. For TC citizens, some TRNC banks offer home loans up to roughly 50-70% LTV, 5-15 year terms — TL-denominated rates are volatile and track central bank policy, and foreign-currency mortgage availability is narrow. For foreign nationals a home loan is rare; most foreign buyers pay cash or use developer instalments. Buyers living in the UK or EU often use equity release / remortgage in their home country. Developer instalment plans (below) are the most practical financing route for many foreign buyers."),
    (7, 4, None,
     "Coastal projects in Northern Cyprus are predominantly priced in GBP; some use EUR or USD. TL-priced listings are rarer (usually older properties aimed at local buyers). Given TL's exchange-rate volatility, sterling- or euro-denominated property offers clearer value preservation for long-term investors. The currency choice also affects market liquidity — GBP dominates coastal resort areas, while TL is more common in the domestic market."),

    (8, 1, None,
     "Tenancy relationships in the TRNC are governed by the Rent (Control) Law and the contract terms. Tenant fundamentals: no eviction without lawful cause during the contract term, deposit returned in full at contract end (absent damage or debt), landlord entry only with prior notice (usually 24 hours) at reasonable hours, annual rent increases bound by the contract and prevailing reasonable/legal rates, landlord responsibility for basic utilities and sanitary conditions, and judicial process for eviction disputes. Courts or rent tribunals resolve disagreements. Contracts should be bilingual (Turkish + English), signed by both parties, and every page initialled."),
    (8, 4, None,
     "Yes — short-term holiday letting is legal in the TRNC and increasingly common. Operated at commercial scale, however, it typically requires a municipal short-term rental / operating permit, income tax declarations, VAT registration and, in some cases, approvals from the Ministry of Tourism and Environment. In gated complexes, the management regulations may restrict short-term letting — always review the management plan before purchase. Airbnb or Booking hosts also face platform fees and accommodation-tax obligations. Professional rental-management companies handle the full stack (turnover, cleaning, tax, reporting) as a packaged service."),

    (10, 0, None,
     "The main taxes tied to property ownership in the TRNC are: 1) Annual property tax — paid to the municipality based on property type, area and location. Amounts are in TL and updated periodically; for apartments it is typically modest but can range from several hundred to several thousand TL depending on size and location. Confirm current rates with the municipality. 2) Rental income tax — declared via an income tax return on rental earnings, using a progressive rate schedule. 3) Capital gains — may apply on resale profit (professional / commercial sellers are subject to different withholding rules). 4) Complex/site service fees — not a tax but a private contractual obligation. Use a TRNC-registered accountant for tax planning."),
    (10, 1, None,
     "The title-transfer fee is generally around 6% of the property value. Statutory reliefs and exemptions change over time: historically, a first-time buyer discount (around 3%) has been applied, and such policies are adjusted periodically. Traditionally buyer and seller split the fee 50/50, but this can be varied by the sales contract. In addition, plan for stamp duty (about 0.5% of the contract price), Land Registry fees, and VAT at 5% on new-build (first-sale) homes. Confirm rates in force on the day of purchase in writing with the Land Registry or your solicitor."),
    (10, 3, None,
     "On resale, expect the following cost items: 1) Title-transfer fee split between buyer and seller (per contract), 2) Estate-agent commission (typically 3-5% + VAT from the seller), 3) Capital-gains tax on the realised profit — exemptions and reliefs vary year on year, 4) Withholding for professional sellers (developers, frequent traders), 5) Legal fees, 6) Any early-repayment or loan-closure charges. Important: declaring a reduced sale price in the contract (common practice elsewhere) is unlawful in the TRNC, creates serious criminal/civil risk for both buyer and seller, and can invalidate the title registration. At Nexos we always advise fully transparent, true-price transactions."),

    (13, 0, None,
     "Healthcare in the TRNC is delivered by both state and private providers. Major state hospitals: Dr. Burhan Nalbantoğlu State Hospital in Nicosia (the largest), Famagusta State Hospital, Dr. Akçiçek State Hospital in Kyrenia. Leading private providers include Near East Hospital (NEU, Nicosia), Kolan British Hospital (Nicosia), University of Kyrenia Hospital and Hayat Hospital in Kyrenia — well-equipped, often internationally accredited and commonly English-speaking. Foreign nationals can access emergency care in state hospitals; private health insurance is strongly recommended for comprehensive treatment (typically 400-1,200 GBP per year). The EU EHIC card is not valid in the TRNC."),
    (13, 2, None,
     "Core emergency numbers: 112 (central emergency / ambulance), 155 (police), 199 (fire). Private hospitals run their own 24/7 emergency lines. For specialist or critical cases, air-ambulance transfer to Turkey (typically Ankara, Istanbul or Adana) is available and covered by most comprehensive private insurance policies. Nexos provides property owners with a 24/7 WhatsApp support line, contact details for partner private hospitals and doctors, and ambulance-coordination guidance."),

    (3, 2, None,
     "Typical purchase costs in the TRNC: 1) Title-transfer fee — about 6% of the property value (first-time-buyer discount may apply on certain dates; confirm with the Land Registry). Traditionally split 50/50 between buyer and seller, though this can be varied by contract. 2) VAT — 5% on new-build (first-sale) homes; generally not applied to land or resale homes. 3) Stamp duty — about 0.5% of the contract price (paid when registering at the Land Registry). 4) Legal fees — typically 1-1.5% of value (starting around 1,000 GBP). 5) Estate-agent commission — usually from the seller (3-5% + VAT); occasionally from the buyer. 6) Land Registry registration and administrative fees. 7) Council of Ministers application fees (foreign buyers). Budget roughly 8-12% of the property value for total additional costs."),
]

EN_NEW = [
    (1, {
        "question": "How serious is the earthquake risk? What should I check for structural safety?",
        "answer": "The TRNC sits near the Eastern Mediterranean seismic belt but is not in the same high-risk zone as Turkey's north-south fault lines. Several felt earthquakes have occurred in recent years without causing significant damage. Even so, seismic safety should be a priority when choosing a property: 1) Prefer newer stock (last 10-15 years) built to current TRNC building codes. 2) Ask for the structural design documents and the building permit, and review the inspection report. 3) Have an engineer or independent surveyor check key parameters — concrete class (C30 or higher is preferred), reinforcement quality, shear-wall ratio. 4) Earthquake insurance is not legally mandatory but strongly recommended (roughly 100-250 GBP per year)."
    }),
    (3, {
        "question": "How are utilities (water, electricity, internet) connected after purchase?",
        "answer": "Utility connections typically work as follows after title transfer: 1) Electricity (KIB-TEK) — apply at your local KIB-TEK office with your title deed, ID and proof of residence; a deposit of around 100-300 GBP is required depending on property size, and any outstanding bills from the previous owner must be settled first. 2) Water — applied for at the municipality; fees and deposits vary by town. In some complexes water is distributed by a shared system and handled by site management. 3) Internet — major providers are Telsim, Turkcell KKTC and Primetel. Fibre is available in most city centres and coastal complexes; packages run 25-80 GBP per month. Installation takes 3-7 working days. At Nexos we manage all utility setup on your behalf via power of attorney, and offer ongoing bill management for absentee owners."
    }),
    (5, {
        "question": "How and through what channels can I transfer the purchase price to the TRNC?",
        "answer": "The TRNC's currency controls are relatively flexible, but every payment should go through a bank and be documented (with reference to the sales contract). Common methods: 1) International SWIFT wire — directly to the seller's TRNC bank account; for large amounts, supporting documentation (sales contract and rationale) may be requested. 2) Open a TRNC bank account in your own name and pay from there — the preferred, fully traceable approach; account opening requires passport, address and reference letter (1-5 working days). 3) Escrow account — a more secure route where funds sit in the solicitor's client account until conditions are met. 4) Wise / Transferwise or similar fintech — cost-effective for small to medium amounts. Important: large cash payments raise anti-money-laundering concerns; always use bank channels and archive bank receipts with the contract. Also check exit-transfer limits and tax implications in your country of origin."
    }),
]

# ---------------------------------------------------------------------------
# DE
# ---------------------------------------------------------------------------

DE_PATCHES = [
    (0, 0, None,
     "Nordzypern zählt seit einigen Jahren zu den dynamischsten Immobilienmärkten des Mittelmeerraums. Seit 2020 sind die Preise in den Küstengebieten deutlich gestiegen, mit jährlichen Wertsteigerungen je nach Lage und Projekt von rund 10-25 % (kein einzelner Wert — stark vom Mikromarkt abhängig). Vorteile: niedrige Einstiegspreise, Preisnotierung in Pfund, 300+ Sonnentage, weitverbreitetes Englisch, Direktflüge in die Türkei, wachsender Tourismussektor und anhaltende Mietnachfrage durch über 20 Universitäten. Vergangene Wertentwicklung garantiert jedoch keine zukünftigen Renditen; unabhängige Due Diligence und Rechtsberatung sind vor jeder Investition unerlässlich."),
    (0, 1, None,
     "Die Quadratmeterpreise in Nordzypern liegen im Allgemeinen deutlich unter den Touristengebieten von Spanien, Südzypern, Griechenland und Italien. Ein strandnahes 1+1-Apartment in Iskele Long Beach wird aktuell für etwa 70.000-130.000 GBP gehandelt; eine vergleichbare Immobilie in Südzypern (Ayia Napa / Larnaka) liegt bei 180.000+ EUR, an der Costa del Sol bei 200.000+ EUR. Preise variieren nach Projekt, Fertigstellungsstand, Ausblick und Grundstücksanteil — aktuelle Zahlen finden Sie in unseren Angeboten."),
    (0, 4, None,
     "Kurzzeitvermietung in Nordzypern ist saisonabhängig. In der Hochsaison (Juni-September) in Iskele Long Beach und Kyrenia liegen die Tagespreise typisch bei: 1+1-Apartments 50-100 GBP, 2+1-Apartments 80-160 GBP, Villen 150-400 GBP. In der Nebensaison fallen sie deutlich. Die jährliche Auslastung mit professionellem Management und guter Lage liegt bei 60-85 %. Kommunale Genehmigung, Mehrwertsteuer-Registrierung und jährliche Einkommensteuererklärung sind erforderlich — der rechtliche und steuerliche Rahmen unterscheidet sich von Langzeitvermietung."),

    (4, 0, None,
     "In Nordzypern gibt es vier Haupttitelarten: "
     "1) Vor-1974-Türkischer Titel (Türk Malı Koçan) — Immobilien, die vor 1974 im Eigentum türkischer Zyprer standen. Rechtlich am stärksten und meist am wertvollsten. "
     "2) Äquivalent-Titel (Eşdeğer) — vergeben an türkische Zyprer, die aus dem Süden vertrieben wurden, als Ausgleich für hinterlassene Immobilien (Punktesystem). Staatlich abgesichert und marktgängig. "
     "3) Zugeteilter Titel (Tahsis / TMD) — vom Staat nach 1974 an Einwanderer aus der Türkei vergeben. Der internationale rechtliche Status ist umstritten und wird ausländischen Käufern in der Regel nicht empfohlen. "
     "4) Ausländertitel / Übertragener Titel — bereits an Ausländer übertragene Titel (mit Zustimmung des Ministerrats); ein neuer ausländischer Käufer durchläuft das Zustimmungsverfahren erneut. "
     "Beauftragen Sie stets vor dem Kauf eine unabhängige anwaltliche Titelrecherche und bewerten Sie das Risikoprofil der Titelart."),
    (4, 1, None,
     "Für türkische Staatsbürger, die keine Zustimmung des Ministerrats benötigen, ist die Titelübertragung in der Regel innerhalb weniger Tage bis 1-2 Wochen abgeschlossen. Für ausländische Käufer ist der Prozess anders: nach dem Gesetz über den Erwerb von Immobilien und langfristigen Pachtverhältnissen (Ausländer) geht der Antrag ans Innenministerium, durchläuft Polizei- und Militärüberprüfung und erhält dann die Zustimmung des Ministerrats. Nach den Änderungen von 2023 beträgt die durchschnittliche Dauer 6-12 Monate, in stark frequentierten Phasen länger. Während dieser Zeit muss der Kaufvertrag beim Grundbuchamt registriert werden (Specific Performance), um den Käufer zu schützen."),
    (4, 2, None,
     "Ja — unbedingt, und für ausländische Käufer ist dies der kritischste Rechtsschritt in Nordzypern. Die Registrierung des Kaufvertrags beim Grundbuchamt innerhalb von 21 Tagen (nach Zahlung der Vertragsstempelsteuer) gewährt dem Käufer den Schutz der 'Specific Performance' nach dem Vertragsgesetz: Der Verkäufer kann die Immobilie nicht weiterverkaufen, keine Hypothek oder Pfandrecht eintragen lassen und nicht zugunsten eines anderen Käufers vom Vertrag zurücktreten. Ein Käufer, der die Registrierung versäumt, riskiert den Verlust aller Rechte bis zum Titelübertragung. Stempelsteuer: ca. 0,5 % des Vertragspreises; Registrierungsgebühren: fixer und wertabhängiger Anteil."),
    (4, 4, None,
     "Ja — wenn Sie im Ausland leben, können Sie Ihrem Anwalt per apostillierter (Haager Konvention) oder durch das TRNC-Konsulat beglaubigter Vollmacht Vollmacht erteilen. In der Türkei beurkundete Vollmachten sind in der TRNC gültig; in anderen Ländern beurkundete benötigen eine Apostille (oder TRNC-Konsulatsbeglaubigung). Die Vollmacht muss die ermächtigten Handlungen ausdrücklich auflisten: Titelübertragung, Antrag beim Ministerrat, Kontoeröffnung, Unterzeichnung notarieller Verträge usw. Einer begrenzten Vollmacht nur für die erforderlichen Handlungen ist einer uneingeschränkten Generalvollmacht vorzuziehen. Gesamtkosten inkl. Übersetzung typisch 100-300 GBP."),

    (5, 0, None,
     "Ja — ausländische natürliche Personen können in Nordzypern mit Zustimmung des Ministerrats Immobilien erwerben. Maßgeblich ist das Gesetz über den Erwerb von Immobilien und langfristigen Pachtverhältnissen (Ausländer) (Nr. 52/2008 und nachfolgende Änderungen). Aktuelle Regelungen erlauben einer ausländischen Person unter bestimmten Voraussetzungen den Erwerb mehrerer Immobilien, wobei kombinierte Fläche und Anzahl gesetzlich begrenzt sind. Da diese Grenzen im Laufe der Zeit mehrfach geändert wurden (zuletzt 2023), empfehlen wir dringend, vor dem Kauf die am Kauftag geltenden Grenzen schriftlich bei Ihrem Anwalt und bei uns zu bestätigen. Türkische Staatsbürger unterliegen diesem Zustimmungsverfahren nicht (siehe nächste Frage)."),
    (5, 1, None,
     "Die Zustimmung des Ministerrats ist die offizielle Genehmigung, die ein ausländischer Staatsbürger für den Immobilienerwerb in der TRNC benötigt. Der beim Innenministerium eingereichte Antrag umfasst in der Regel: Passkopie, Wohnsitznachweis, Führungszeugnis (apostilliert aus dem Herkunftsland), Passfotos, Kopie des Kaufvertrags, Grundbuchauszug und Antragsformulare. Ablauf: Antrag → Sicherheitsüberprüfung durch Polizei und Militär → Entscheidung des Ministerrats → Titelübertragung nach Genehmigung. Durchschnittliche Dauer nach 2023: 6-12 Monate. Die Registrierung des Kaufvertrags beim Grundbuchamt (Specific Performance) während dieses Zeitraums ist unerlässlich. Ihr Anwalt bereitet den Antrag vor und begleitet ihn."),
    (5, 2, None,
     "Ja — für türkische Staatsbürger gelten wichtige Ausnahmen. TC-Bürger unterliegen nicht dem Zustimmungsverfahren des Ministerrats: Die Titelübertragung erfolgt direkt beim Grundbuchamt und kann innerhalb weniger Tage abgeschlossen sein. Bearbeitet wird mit türkischem Personalausweis oder Reisepass. Die für Ausländer geltenden Beschränkungen bezüglich Immobilienanzahl und Grundstücksfläche gelten für TC-Bürger nicht in gleicher Form. Dies verschafft TC-Bürgern einen deutlichen Vorteil in Bezug auf Ablauf, Zeit und Rechtsverfahren."),
    (5, 4, None,
     "Ja — in der TRNC können Sie eine registrierte Limited Company (Ltd.) gründen und darüber Immobilien erwerben; in bestimmten Fällen ermöglicht dies Investoren, die Grenzen für ausländische Einzelpersonen zu überschreiten. Die Gründung dauert ca. 2-4 Wochen; die Gesamtkosten (Anwalt, Eintragung, Stammkapital) liegen bei 2.000-4.000 GBP. Beachten Sie die laufenden Kosten und Pflichten: Körperschaftsteuer bei Veräußerungsgewinn, MwSt.-Besonderheiten, jährliche Prüfung, Buchhaltergebühren und Mietertragsberichterstattung. Für Portfolio-Investitionen effizient; bei einer Einzelimmobilie ist der Erwerb als natürliche Person in der Regel kosteneffektiver. Vor der Entscheidung sollte eine Gesamtkostenmodellierung mit einem Steuerberater erfolgen."),

    (6, 0, None,
     "Ja — ausländische Immobilienbesitzer in der TRNC können eine 'vorübergehende Aufenthaltsgenehmigung' beantragen. Der Antrag wird beim Innenministerium / Einwanderungsbehörde mit folgenden Unterlagen gestellt: Reisepass und Kopien, Titelurkunde oder Kaufvertrag, TRNC-Gesundheitsprüfungsbericht, Führungszeugnis, zwei Passfotos, Einkommens-/Bankkontonachweis und Antragsgebühren. Die vorübergehende Aufenthaltsgenehmigung wird meist für 1 Jahr erteilt und ist bei weiterhin erfüllten Bedingungen verlängerbar. Da die Anforderungen sich ändern, bestätigen Sie die aktuellen Kriterien vor Antragstellung bei der Einwanderungsbehörde oder Ihrem Anwalt."),
    (6, 2, None,
     "Die TRNC-Staatsbürgerschaft ist unter bestimmten Voraussetzungen möglich, wird aber nicht automatisch durch Immobilienbesitz erteilt. Hauptwege: 1) Durch Heirat — mit TRNC-Staatsbürger nach einer gesetzlich festgelegten Mindestwohnsitzdauer, 2) Langzeitaufenthalt — ununterbrochener rechtmäßiger Aufenthalt über die gesetzlich vorgesehenen Jahre mit nachgewiesener Bindung an das Land, 3) Ausnahmegründe — besondere Leistungen / Investitionen. Das Verfahren ist komplex und durch mehrfach geänderte Gesetze geprägt — aktuelle Wartezeiten, Sprach-/Kulturprüfungen und sonstige Kriterien variieren im Zeitverlauf. Vor Antragstellung sollte eine schriftliche Einschätzung zum aktuellen Rechtsstand bei einem im Einwanderungsrecht spezialisierten Anwalt eingeholt werden."),

    (7, 0, None,
     "Der nordzypriotische Immobilienmarkt ist in den letzten Jahren insbesondere in Küstengebieten deutlich gewachsen — vergangene Wertentwicklungen sind jedoch keine Garantie für künftige Renditen. Eine angemessene langfristige Nettomietrendite liegt bei rund 4-8 % pro Jahr; Kurzzeitvermietung mit professionellem Management kann 6-12 % erreichen. Wertsteigerungen schwanken stark nach Jahr und Lage. Typische Muster: Universitätsnähe — stabile Mietnachfrage und moderate Wertsteigerung; Küstentourismus (Long Beach, Bafra, Esentepe) — höhere Airbnb-Renditen, aber hohe Saisonvolatilität; Zentral-Kyrenia — etablierte Nachfrage und stabile Langzeitmieter. Für jede Investition sind unabhängige Due Diligence und Cashflow-Modellierung unerlässlich."),
    (7, 2, None,
     "Hypothekenangebote in der TRNC sind begrenzt. Für TC-Bürger bieten einige TRNC-Banken Wohnungsbaudarlehen bis zu etwa 50-70 % Beleihungswert, 5-15 Jahre Laufzeit — TL-Zinssätze sind volatil und folgen der Zentralbankpolitik; Fremdwährungsdarlehen sind knapp. Für ausländische Staatsbürger ist ein Hypothekendarlehen selten; die meisten zahlen bar oder nutzen Ratenzahlungen des Bauträgers. Käufer aus UK oder EU nutzen oft Equity Release / Remortgage in ihrem Heimatland. Bauträger-Ratenpläne (siehe unten) sind häufig der praktischste Finanzierungsweg."),
    (7, 4, None,
     "Küstenprojekte in Nordzypern werden überwiegend in GBP ausgepreist; einige nutzen EUR oder USD. TL-Preise sind selten (meist ältere, an lokale Käufer gerichtete Immobilien). Angesichts der Wechselkursvolatilität der TL bieten in Sterling oder Euro notierte Immobilien für langfristige Anleger einen klareren Werterhalt. Die Währungswahl beeinflusst auch die Marktliquidität — an der Küste dominiert GBP, im Binnenmarkt ist TL verbreiteter."),

    (8, 1, None,
     "Mietverhältnisse in der TRNC unterliegen dem Mietkontrollgesetz und den Vertragsbedingungen. Grundrechte des Mieters: keine Kündigung ohne rechtmäßigen Grund während der Vertragslaufzeit, Rückgabe der Kaution in voller Höhe am Vertragsende (ohne Schäden oder Rückstände), Betreten durch den Vermieter nur nach Ankündigung (in der Regel 24 Stunden) zu angemessener Zeit, jährliche Mieterhöhungen vertraglich und an geltende angemessene/gesetzliche Sätze gebunden, Verantwortung des Vermieters für Grundversorgung und sanitäre Verhältnisse, gerichtliches Verfahren bei Kündigungsstreitigkeiten. Gerichte oder Mietkontrollstellen lösen Auseinandersetzungen. Verträge sollten zweisprachig (Türkisch + Englisch) sein, von beiden Parteien unterzeichnet und jede Seite paraphiert werden."),
    (8, 4, None,
     "Ja — Kurzzeit-Ferienvermietung ist in der TRNC legal und zunehmend verbreitet. Im gewerblichen Umfang erfordert sie typischerweise eine städtische Kurzzeit-/Betriebsgenehmigung, Einkommensteuererklärungen, MwSt.-Registrierung und gegebenenfalls Zustimmungen des Ministeriums für Tourismus und Umwelt. In Wohnanlagen kann die Verwaltungsordnung Kurzzeitvermietung einschränken — prüfen Sie den Verwaltungsplan vor dem Kauf. Airbnb- oder Booking-Gastgeber haben zusätzlich Plattformgebühren und Unterkunftssteuerpflichten. Professionelle Vermietungsunternehmen übernehmen den gesamten Prozess (Gastwechsel, Reinigung, Steuer, Reporting) als Komplettdienst."),

    (10, 0, None,
     "Die wichtigsten steuerlichen Verpflichtungen beim Immobilienbesitz in der TRNC: 1) Jährliche Grundsteuer — an die Gemeinde nach Immobilientyp, Fläche und Lage gezahlt. Beträge in TL, periodisch aktualisiert; für Wohnungen meist moderat, je nach Größe und Lage von wenigen Hundert bis einigen Tausend TL. Aktuelle Sätze bei der Gemeinde bestätigen. 2) Mieteinkommensteuer — Einkommensteuererklärung über Mieteinnahmen, progressive Tarife. 3) Veräußerungsgewinne — können beim Wiederverkauf fällig werden (professionelle/gewerbliche Verkäufer unterliegen anderen Quellensteuerregeln). 4) Anlagen-/Site-Gebühren — keine Steuer, sondern vertragliche Verpflichtung. Für Steuerplanung einen in der TRNC registrierten Buchhalter konsultieren."),
    (10, 1, None,
     "Die Titelübertragungsgebühr beträgt in der Regel rund 6 % des Immobilienwerts. Gesetzliche Erleichterungen und Freibeträge ändern sich im Zeitverlauf: historisch wurde eine Erstkäuferermäßigung (ca. 3 %) angewandt, solche Politiken werden periodisch angepasst. Traditionell teilen sich Käufer und Verkäufer 50:50, kann jedoch durch den Vertrag abweichen. Zusätzlich einzuplanen: Stempelsteuer (ca. 0,5 % des Vertragspreises), Grundbuchgebühren und MwSt. 5 % auf neue (Erstverkauf) Wohnungen. Am Kauftag geltende Sätze schriftlich beim Grundbuchamt oder Anwalt bestätigen lassen."),
    (10, 3, None,
     "Beim Wiederverkauf fallen folgende Kosten an: 1) Aufteilung der Titelübertragungsgebühr (per Vertrag), 2) Maklerprovision (üblicherweise 3-5 % + MwSt. vom Verkäufer), 3) Veräußerungsgewinnsteuer auf den realisierten Gewinn — Freibeträge ändern sich jährlich, 4) Quellensteuer für professionelle Verkäufer (Bauträger, häufige Händler), 5) Anwaltskosten, 6) ggf. Vorfälligkeitsentschädigung. Wichtig: Die Angabe eines niedrigeren Verkaufspreises im Vertrag (anderswo verbreitete Praxis) ist in der TRNC unzulässig, birgt erhebliche straf-/zivilrechtliche Risiken für Käufer und Verkäufer und kann die Titelregistrierung ungültig machen. Bei Nexos empfehlen wir stets transparente Transaktionen zum wahren Preis."),

    (13, 0, None,
     "Die medizinische Versorgung in der TRNC erfolgt durch staatliche und private Einrichtungen. Wichtige staatliche Krankenhäuser: Dr. Burhan Nalbantoğlu Staatskrankenhaus in Nikosia (das größte), Staatskrankenhaus Famagusta, Dr. Akçiçek Staatskrankenhaus in Kyrenia. Führende private Anbieter: Near East Hospital (NEU, Nikosia), Kolan British Hospital (Nikosia), Universitätskrankenhaus Kyrenia und Hayat Hospital in Kyrenia — gut ausgestattet, oft international akkreditiert und meist englischsprachig. Ausländer haben Zugang zur Notfallversorgung in staatlichen Krankenhäusern; für umfassende Behandlung wird eine private Krankenversicherung dringend empfohlen (typisch 400-1.200 GBP jährlich). Die EU-EHIC-Karte gilt in der TRNC nicht."),
    (13, 2, None,
     "Grundlegende Notrufnummern: 112 (zentraler Notruf / Krankenwagen), 155 (Polizei), 199 (Feuerwehr). Private Krankenhäuser betreiben eigene 24/7-Notaufnahmen. In schweren und spezialisierten Fällen ist eine Luftambulanz-Verlegung in die Türkei (meist Ankara, Istanbul, Adana) verfügbar und von den meisten umfassenden privaten Versicherungen abgedeckt. Nexos bietet Immobilienbesitzern eine 24/7 WhatsApp-Supportleitung, Kontakte zu Partnerkrankenhäusern und -ärzten sowie Unterstützung bei der Krankenwagenkoordination."),

    (3, 2, None,
     "Typische Kaufkosten in der TRNC: 1) Titelübertragungsgebühr — ca. 6 % des Immobilienwerts (eine Erstkäuferermäßigung kann gelten; beim Grundbuchamt bestätigen). Traditionell 50:50 zwischen Käufer und Verkäufer, kann jedoch vertraglich anders geregelt werden. 2) MwSt. — 5 % bei Neubauten (Erstverkauf); grundsätzlich nicht bei Grundstücken oder Wiederverkäufen. 3) Stempelsteuer — ca. 0,5 % des Vertragspreises (bei Registrierung im Grundbuchamt). 4) Anwaltskosten — typisch 1-1,5 % des Werts (ab ca. 1.000 GBP). 5) Maklerprovision — meist vom Verkäufer (3-5 % + MwSt.); gelegentlich vom Käufer. 6) Grundbuch-Registrierung und Verwaltungskosten. 7) Gebühren für den Antrag beim Ministerrat (ausländische Käufer). Insgesamt etwa 8-12 % des Immobilienwerts für zusätzliche Kosten einplanen."),
]

DE_NEW = [
    (1, {
        "question": "Wie groß ist das Erdbebenrisiko? Worauf sollte man bei der Bausicherheit achten?",
        "answer": "Die TRNC liegt nahe dem östlichen Mittelmeer-Seismikgürtel, befindet sich jedoch nicht in der gleichen Hochrisikozone wie die Nord-Süd-Verwerfungslinien der Türkei. In den letzten Jahren traten mehrere spürbare Erdbeben ohne nennenswerte Schäden auf. Bebensicherheit sollte dennoch Priorität haben: 1) Bevorzugen Sie neueren Bestand (letzte 10-15 Jahre) nach aktuellen TRNC-Baunormen. 2) Verlangen Sie die Statikpläne und die Baugenehmigung und prüfen Sie das Prüfgutachten. 3) Lassen Sie einen Ingenieur oder unabhängigen Gutachter zentrale Parameter prüfen — Betonfestigkeitsklasse (C30 oder höher), Bewehrungsqualität, Wandscheibenanteil. 4) Eine Erdbebenversicherung ist gesetzlich nicht zwingend, aber dringend empfohlen (ca. 100-250 GBP/Jahr)."
    }),
    (3, {
        "question": "Wie werden Wasser, Strom und Internet nach dem Kauf angeschlossen?",
        "answer": "Nach der Titelübertragung laufen die Anschlüsse typischerweise wie folgt: 1) Strom (KIB-TEK) — Antrag beim lokalen KIB-TEK-Büro mit Titelurkunde, Ausweis und Wohnsitznachweis; Kaution ca. 100-300 GBP je nach Größe, offene Rechnungen des Vorbesitzers müssen vorab beglichen sein. 2) Wasser — Antrag bei der Gemeinde; Gebühren und Kaution variieren je Stadt. In manchen Komplexen wird Wasser zentral verteilt und vom Siteverwalter abgerechnet. 3) Internet — Hauptanbieter sind Telsim, Turkcell KKTC und Primetel. Glasfaser ist in den meisten Stadtzentren und Küstenanlagen verfügbar; Pakete 25-80 GBP monatlich. Installation 3-7 Werktage. Bei Nexos übernehmen wir die Anschlusseinrichtung per Vollmacht und bieten laufendes Rechnungsmanagement für Eigentümer, die nicht vor Ort leben."
    }),
    (5, {
        "question": "Wie und über welche Kanäle kann ich den Kaufpreis in die TRNC transferieren?",
        "answer": "Die TRNC-Devisenkontrolle ist relativ flexibel, aber jede Zahlung sollte über eine Bank erfolgen und dokumentiert sein (mit Bezug zum Kaufvertrag). Gängige Wege: 1) Internationale SWIFT-Überweisung — direkt auf das TRNC-Konto des Verkäufers; bei hohen Beträgen können Nachweise (Kaufvertrag, Begründung) angefordert werden. 2) Eröffnung eines TRNC-Bankkontos und Zahlung von dort — der bevorzugte, vollständig nachvollziehbare Weg; für die Kontoeröffnung reichen Reisepass, Adresse und Referenzschreiben (1-5 Werktage). 3) Treuhandkonto — sicherere Option, Geld bleibt auf dem Anwaltstreuhandkonto bis zur Bedingungserfüllung. 4) Wise / Transferwise oder ähnliche Fintech — kostengünstig für kleine bis mittlere Beträge. Wichtig: hohe Barzahlungen werfen Geldwäsche-Probleme auf; nutzen Sie stets Bankkanäle und archivieren Sie Bankbelege mit dem Vertrag. Prüfen Sie auch die Ausfuhr- und Steuerbestimmungen in Ihrem Herkunftsland."
    }),
]

# ---------------------------------------------------------------------------
# RU
# ---------------------------------------------------------------------------

RU_PATCHES = [
    (0, 0, None,
     "Северный Кипр в последние годы стал одним из наиболее динамичных рынков недвижимости Средиземноморья. С 2020 года цены в прибрежных курортных зонах заметно выросли; годовой прирост стоимости варьируется примерно в диапазоне 10-25% в зависимости от локации и проекта (единого показателя нет — многое зависит от конкретного микрорынка). Среди ключевых преимуществ: низкий порог входа, ценообразование в фунтах стерлингов, 300+ солнечных дней в году, широкое использование английского языка, прямые рейсы в Турцию, развивающийся туризм и постоянный спрос на аренду со стороны более 20 университетов. Однако прошлая динамика не гарантирует будущей доходности; независимый аудит и юридическое сопровождение обязательны до инвестиции."),
    (0, 1, None,
     "Цены за м² на Северном Кипре обычно заметно ниже туристических зон Испании, Южного Кипра, Греции и Италии. Например, апартаменты 1+1 у моря в районе Long Beach (Искеле) сейчас торгуются примерно за 70 000-130 000 GBP, тогда как сопоставимая недвижимость в Южном Кипре (Айя-Напа / Ларнака) стоит от 180 000 EUR, а на Коста-дель-Соль — от 200 000 EUR. Цены зависят от проекта, стадии строительства, вида и доли земли — актуальные цифры смотрите в наших объявлениях."),
    (0, 4, None,
     "Доход от краткосрочной аренды на Северном Кипре сезонный. В высокий сезон (июнь-сентябрь) в Лонг-Бич и Кирении типичные дневные ставки: апартаменты 1+1 — 50-100 GBP, 2+1 — 80-160 GBP, виллы — 150-400 GBP. В низкий сезон ставки заметно снижаются. Годовая заполняемость при профессиональном управлении и хорошей локации составляет 60-85%. Требуются муниципальная лицензия на краткосрочную аренду, регистрация НДС и ежегодная декларация о доходах — правовой и налоговый режим отличается от долгосрочной аренды."),

    (4, 0, None,
     "На Северном Кипре распространены четыре основных типа титулов на недвижимость: "
     "1) Турецкий титул до 1974 г. (Türk Malı Koçan) — имущество, находившееся в собственности турок-киприотов до 1974 года. Юридически самый надёжный и, как правило, самый ценный тип. "
     "2) Эквивалентный титул (Eşdeğer) — выдан турко-киприотам, переселившимся с юга, в обмен на оставленное там имущество (система эквивалентных баллов). Государственная гарантия, распространён на рынке. "
     "3) Распределённый титул (Tahsis / TMD) — распределён государством после 1974 года переселенцам из Турции. Его международно-правовой статус может быть спорным; иностранным покупателям обычно не рекомендуется. "
     "4) Иностранный / переоформленный титул — титулы, ранее переданные иностранцам (с согласия Совета министров); новому иностранному покупателю предстоит пройти процедуру согласия заново. "
     "Перед покупкой обязательно заказывайте независимую юридическую проверку титула (title search) и оценивайте риск-профиль типа титула."),
    (4, 1, None,
     "Для граждан Турции, которым не требуется согласие Совета министров, передача титула обычно завершается в течение нескольких дней или 1-2 недель после подготовки документов. Для иностранных покупателей процесс иной: по Закону о приобретении недвижимости и долгосрочной аренде (иностранцами) заявление подаётся в Министерство внутренних дел, проходит проверки полиции и военного ведомства, после чего выдаётся согласие Совета министров. После поправок 2023 года средний срок — 6-12 месяцев, в периоды загруженности может быть дольше. В этот период договор купли-продажи должен быть зарегистрирован в Земельном кадастре (Specific Performance) для защиты покупателя."),
    (4, 2, None,
     "Да — обязательно; для иностранных покупателей это самый критичный правовой шаг. Регистрация договора купли-продажи в Земельном кадастре в течение 21 дня (после уплаты гербового сбора по договору) обеспечивает покупателю защиту 'Specific Performance' по Закону о договорах: продавец не может перепродать имущество, наложить ипотеку или арест, отказаться от договора в пользу другого покупателя. Покупатель, не зарегистрировавший договор, рискует утратить все права до завершения передачи титула. Гербовый сбор — около 0,5% от цены договора; регистрационные сборы имеют фиксированную и стоимостную составляющие."),
    (4, 4, None,
     "Да — живя за рубежом, вы можете наделить своего юриста полномочиями через доверенность с апостилем (Гаагская конвенция) или заверенную консульством ТРСК. Доверенности, оформленные у турецких нотариусов, действительны в ТРСК; оформленные в других странах — нуждаются в апостиле (или консульском заверении ТРСК). Доверенность должна прямо перечислять полномочия: передача титула, подача заявления в Совет министров, открытие банковского счёта, подписание нотариальных договоров и т.д. Предпочтительна ограниченная доверенность, охватывающая только нужные действия, а не неограниченная генеральная. Общая стоимость с переводом — 100-300 GBP."),

    (5, 0, None,
     "Да — иностранные физические лица могут приобретать недвижимость в ТРСК с согласия Совета министров. Применимое законодательство — Закон о приобретении недвижимости и долгосрочной аренде (иностранцами) (№ 52/2008 и последующие поправки). Действующие нормы позволяют иностранному лицу при определённых условиях приобретать более одного объекта с ограничениями по суммарной площади и количеству единиц. Поскольку эти пределы неоднократно менялись (последние изменения — 2023), настоятельно рекомендуется письменно уточнить актуальные пределы на день сделки у вашего юриста и у нас. Граждане Турции не подпадают под данную процедуру (см. следующий вопрос)."),
    (5, 1, None,
     "Согласие Совета министров — это официальное разрешение, необходимое иностранному гражданину для приобретения недвижимости в ТРСК. Заявление подаётся в Министерство внутренних дел и обычно содержит: копию паспорта, подтверждение адреса, справку об отсутствии судимости (апостиль из страны происхождения), паспортные фото, копию договора купли-продажи, титул и отчёт о проверке, форму заявления. Процесс: заявление → проверки полиции и военных → решение Совета министров → передача титула по одобрении. Средний срок после 2023 — 6-12 месяцев. В этот период необходимо зарегистрировать договор в Земельном кадастре (Specific Performance). Подготовкой и сопровождением занимается ваш юрист."),
    (5, 2, None,
     "Да — для граждан Турции предусмотрены важные исключения. ТС-граждане не обязаны проходить процедуру согласия Совета министров: титул передаётся напрямую в Земельном кадастре и может быть оформлен за несколько дней. Операции проводятся по ТС ID или паспорту. Ограничения по количеству объектов и площади, действующие для иностранцев, к гражданам Турции в том же виде не применяются. Это даёт гражданам Турции заметное преимущество в сроке, процедуре и правовом режиме."),
    (5, 4, None,
     "Да — в ТРСК можно учредить зарегистрированную компанию с ограниченной ответственностью (Ltd.) и приобретать недвижимость через неё; в ряде случаев это позволяет инвестору преодолеть ограничения, действующие для иностранных физических лиц. Учреждение занимает 2-4 недели; совокупная стоимость (юристы, регистрация, уставный капитал) — 2 000-4 000 GBP. Учтите постоянные расходы: корпоративный налог на прибыль от перепродажи, особенности НДС, ежегодный аудит, услуги бухгалтера, декларирование арендного дохода. Для портфельных инвестиций структура эффективна; для одной квартиры зачастую выгоднее покупка на физическое лицо. До решения проведите моделирование затрат с налоговым консультантом."),

    (6, 0, None,
     "Да — иностранцы-собственники недвижимости в ТРСК могут подать заявление на 'временный вид на жительство'. Документы подаются в Министерство внутренних дел / Миграционную службу: паспорт и копии, титул или договор купли-продажи, медицинское обследование (в ТРСК), справка о несудимости, 2 фото на паспорт, подтверждение достаточного дохода или банковского остатка, заявление с пошлиной. Временный ВНЖ обычно выдаётся на 1 год и продлевается при сохранении условий. Поскольку требования меняются по годам, актуальные критерии уточняйте до подачи в Миграционной службе или у юриста."),
    (6, 2, None,
     "Гражданство ТРСК возможно при определённых условиях, но владение недвижимостью не даёт его автоматически. Основные пути: 1) По браку — минимально установленный законом срок проживания как супруга гражданина ТРСК до подачи заявления, 2) Длительное проживание — непрерывное легальное проживание в течение предусмотренного законом числа лет с подтверждением связей со страной, 3) Исключительные основания — особая заслуга / инвестиция. Процедура сложная и регулируется многократно изменявшимся законодательством — сроки ожидания, экзамены по языку/культуре и иные критерии меняются. До подачи получите письменное заключение по действующему режиму у юриста, специализирующегося на миграционном праве."),

    (7, 0, None,
     "Рынок недвижимости Северного Кипра значительно вырос в последние годы, особенно в прибрежных зонах, — но прошлая динамика не гарантирует будущей доходности. Разумная долгосрочная арендная доходность (нетто, после расходов) — около 4-8% в год; краткосрочная (курортная) аренда при профессиональном управлении может достигать 6-12%. Прирост стоимости сильно различается по годам и локациям. Типичные паттерны: рядом с университетами — стабильный спрос и умеренный рост; прибрежный туризм (Long Beach, Bafra, Esentepe) — выше Airbnb-доходность, но высокая сезонная волатильность; центр Кирении — устойчивый спрос и стабильные долгосрочные арендаторы. Для каждой инвестиции необходимы независимая проверка и моделирование денежного потока."),
    (7, 2, None,
     "Ипотечные возможности в ТРСК ограничены. Для граждан Турции некоторые банки ТРСК предлагают жилищные кредиты до 50-70% LTV на 5-15 лет — ставки по кредитам в TL волатильны и следуют политике центрального банка, валютные кредиты редки. Для иностранных граждан ипотека встречается редко; большинство иностранных покупателей платят наличными или используют рассрочку от застройщика. Покупатели из Великобритании и ЕС часто используют equity release / remortgage на родине. Рассрочка от застройщика (см. ниже) — наиболее практичный способ финансирования для многих иностранных покупателей."),
    (7, 4, None,
     "Прибрежные проекты Северного Кипра преимущественно оцениваются в GBP; некоторые — в EUR или USD. Объявления в TL редки (обычно это вторичное жильё, ориентированное на местных покупателей). С учётом волатильности курса TL недвижимость, номинированная в фунтах или евро, обеспечивает более понятное сохранение стоимости для долгосрочного инвестора. Выбор валюты влияет и на ликвидность — в курортных прибрежных зонах преобладает GBP, на внутреннем рынке — TL."),

    (8, 1, None,
     "Арендные отношения в ТРСК регулируются Законом о контроле арендной платы и условиями договора. Базовые права арендатора: нельзя выселить без законных оснований в период действия договора, возврат депозита в полном объёме в конце срока (при отсутствии ущерба и задолженности), доступ арендодателя только с уведомлением (обычно за 24 часа) в разумное время, годовое повышение аренды ограничено договором и действующими разумными/законными ставками, ответственность арендодателя за базовые коммуникации и санитарные условия, судебная процедура в спорах о выселении. Споры решают суды или органы контроля арендной платы. Договоры должны быть двуязычными (турецкий + английский), подписаны обеими сторонами, каждая страница парафирована."),
    (8, 4, None,
     "Да — краткосрочная курортная аренда в ТРСК легальна и становится всё более распространённой. В коммерческих масштабах обычно требуется муниципальная лицензия на краткосрочную аренду, декларирование доходов, регистрация НДС и в ряде случаев разрешения Министерства туризма и окружающей среды. В охраняемых комплексах регламент может ограничивать краткосрочную аренду — обязательно ознакомьтесь с правилами управления до покупки. Хозяева на Airbnb и Booking сталкиваются с комиссиями платформ и обязательствами по туристическому сбору. Профессиональные управляющие компании берут на себя весь процесс (заезды, уборка, налоги, отчётность) как пакетную услугу."),

    (10, 0, None,
     "Основные налоги, связанные с владением недвижимостью в ТРСК: 1) Ежегодный налог на имущество — выплачивается муниципалитету в зависимости от типа, площади и локации. Суммы в TL, периодически пересматриваются; для квартир обычно умеренные, но могут составлять от нескольких сотен до нескольких тысяч TL в зависимости от размера и места. Актуальные ставки уточняйте в муниципалитете. 2) Налог на арендный доход — декларируется через подоходную налоговую декларацию, прогрессивная шкала. 3) Налог на прирост капитала — может применяться при перепродаже (для профессиональных/коммерческих продавцов действуют иные правила удержания). 4) Плата за обслуживание комплекса — не налог, а договорное обязательство. Для налогового планирования используйте зарегистрированного в ТРСК бухгалтера."),
    (10, 1, None,
     "Комиссия за передачу титула обычно около 6% от стоимости недвижимости. Льготы и освобождения меняются во времени: исторически применяется скидка для покупателей впервые (около 3%), такие политики периодически корректируются. Традиционно покупатель и продавец делят комиссию 50/50, но это может быть иначе оговорено договором. Также учитывайте: гербовый сбор (около 0,5% цены договора), сборы Земельного кадастра и НДС 5% на новое жильё (первая продажа). Актуальные ставки на день сделки получайте в письменной форме в Земельном кадастре или у юриста."),
    (10, 3, None,
     "При перепродаже имейте в виду следующие статьи затрат: 1) Разделение комиссии за передачу титула (по договору), 2) Агентская комиссия (обычно 3-5% + НДС с продавца), 3) Налог на прирост капитала на реализованную прибыль — льготы меняются ежегодно, 4) Удержание для профессиональных продавцов (застройщики, частые трейдеры), 5) Юридические расходы, 6) Возможные комиссии за досрочное погашение кредита. Важно: занижение цены в договоре (распространённая практика в других странах) незаконно в ТРСК, создаёт серьёзный уголовно-/гражданско-правовой риск для обеих сторон и может сделать регистрацию титула недействительной. Nexos всегда рекомендует прозрачные сделки по реальной цене."),

    (13, 0, None,
     "Медицинская помощь в ТРСК оказывается как государственными, так и частными учреждениями. Крупные государственные больницы: Государственная больница доктора Бурхана Налбантоглу в Никосии (крупнейшая), Государственная больница Фамагусты, Государственная больница доктора Акчичека в Кирении. Ведущие частные клиники: Near East Hospital (NEU, Никосия), Kolan British Hospital (Никосия), Больница университета Кирении и Hayat Hospital в Кирении — хорошо оборудованы, часто имеют международную аккредитацию и англоязычный персонал. Иностранцы могут получать экстренную помощь в государственных больницах; для комплексного лечения настоятельно рекомендуется частная медицинская страховка (обычно 400-1 200 GBP в год). Карта EU EHIC в ТРСК не действует."),
    (13, 2, None,
     "Основные номера экстренных служб: 112 (единый экстренный / скорая), 155 (полиция), 199 (пожарная). У частных больниц есть собственные круглосуточные линии экстренной помощи. В тяжёлых и специализированных случаях возможна санитарная авиация в Турцию (Анкара, Стамбул, Адана) — это покрывается большинством полноценных частных страховок. Nexos предоставляет владельцам круглосуточную линию поддержки в WhatsApp, контакты партнёрских частных больниц и врачей, помощь в координации скорой помощи."),

    (3, 2, None,
     "Типичные расходы при покупке в ТРСК: 1) Комиссия за передачу титула — около 6% от стоимости (может действовать скидка для впервые покупающих; уточняйте в Земельном кадастре). Традиционно делится 50/50 между покупателем и продавцом, но договором можно изменить. 2) НДС — 5% на новое жильё (первая продажа); как правило не применяется к земле и вторичному рынку. 3) Гербовый сбор — около 0,5% цены договора (при регистрации в кадастре). 4) Услуги юриста — обычно 1-1,5% от стоимости (от 1 000 GBP). 5) Агентская комиссия — обычно с продавца (3-5% + НДС); иногда с покупателя. 6) Регистрация в кадастре и административные сборы. 7) Сборы по заявке в Совет министров (для иностранцев). Общие дополнительные расходы планируйте в диапазоне 8-12% от стоимости недвижимости."),
]

RU_NEW = [
    (1, {
        "question": "Насколько велика сейсмическая опасность? На что смотреть с точки зрения прочности здания?",
        "answer": "ТРСК расположена вблизи восточно-средиземноморского сейсмического пояса, но не относится к зоне столь высокого риска, как разломы Северной Турции. За последние годы происходили ощутимые землетрясения без существенного ущерба. Тем не менее сейсмическая безопасность должна быть приоритетом при выборе недвижимости: 1) Отдавайте предпочтение современному фонду (последние 10-15 лет), построенному по действующим строительным нормам ТРСК. 2) Запросите проектную документацию (статика) и разрешение на строительство, ознакомьтесь с актом приёмки. 3) Попросите инженера или независимого оценщика проверить ключевые параметры — класс бетона (предпочтительно C30 и выше), качество арматуры, процент несущих стен. 4) Страхование от землетрясения законом не обязательно, но настоятельно рекомендуется (примерно 100-250 GBP в год)."
    }),
    (3, {
        "question": "Как подключаются вода, электричество и интернет после покупки?",
        "answer": "После передачи титула коммунальные услуги обычно подключаются так: 1) Электричество (KIB-TEK) — подача заявления в местное отделение KIB-TEK с титулом, удостоверением личности и подтверждением адреса; депозит около 100-300 GBP в зависимости от размера, все счета предыдущего владельца должны быть закрыты. 2) Вода — подача в муниципалитет; пошлины и депозиты разнятся по городам. В некоторых комплексах вода подаётся по общей системе, вопросы решаются с администрацией комплекса. 3) Интернет — основные провайдеры Telsim, Turkcell KKTC и Primetel. Оптоволокно есть в большинстве центров городов и в прибрежных комплексах; пакеты от 25 до 80 GBP в месяц. Подключение 3-7 рабочих дней. Nexos организует все подключения по доверенности и предлагает управление счетами для владельцев, проживающих за рубежом."
    }),
    (5, {
        "question": "Как и через какие каналы перевести оплату в ТРСК?",
        "answer": "Валютный контроль в ТРСК относительно гибкий, но каждый платёж должен проходить через банк и быть подтверждён документами (со ссылкой на договор купли-продажи). Распространённые способы: 1) Международный SWIFT-перевод — прямо на счёт продавца в банке ТРСК; при крупных суммах могут запросить подтверждение (договор, обоснование). 2) Открыть собственный счёт в банке ТРСК и платить с него — предпочтительный, полностью прозрачный путь; для открытия достаточно паспорта, адреса и рекомендательного письма (1-5 рабочих дней). 3) Эскроу-счёт — более безопасный вариант: средства на клиентском счёте юриста до выполнения условий. 4) Wise / Transferwise и аналогичные финтех-сервисы — экономично для малых и средних сумм. Важно: крупные наличные оплаты вызывают вопросы по противодействию отмыванию; всегда используйте банковские каналы и храните банковские выписки вместе с договором. Проверьте также лимиты и налоговые правила по экспорту капитала в вашей стране."
    }),
]

# ---------------------------------------------------------------------------
# FA
# ---------------------------------------------------------------------------

FA_PATCHES = [
    (0, 0, None,
     "قبرس شمالی در سال‌های اخیر یکی از پویاترین بازارهای املاک مدیترانه بوده است. از سال ۲۰۲۰ قیمت‌ها در مناطق ساحلی به‌طور محسوسی افزایش یافته و رشد سالانه ارزش بسته به موقعیت و پروژه تقریباً در بازه ۱۰-۲۵ درصد قرار گرفته است (رقم واحدی وجود ندارد — به بازار خرد وابسته است). از مزایای کلیدی می‌توان به ورود آسان، قیمت‌گذاری بر مبنای پوند، بیش از ۳۰۰ روز آفتابی در سال، رواج زبان انگلیسی، پروازهای مستقیم به ترکیه، گردشگری در حال رشد و تقاضای ثابت اجاره از سوی بیش از ۲۰ دانشگاه اشاره کرد. با این حال عملکرد گذشته تضمین بازدهی آینده نیست؛ بررسی مستقل و مشاوره حقوقی پیش از سرمایه‌گذاری ضروری است."),
    (0, 1, None,
     "قیمت هر مترمربع در قبرس شمالی عموماً پایین‌تر از مناطق گردشگری اسپانیا، قبرس جنوبی، یونان و ایتالیا است. برای مثال آپارتمان ۱+۱ کنار ساحل در منطقه Long Beach ایسکله در حال حاضر حدود ۷۰٬۰۰۰-۱۳۰٬۰۰۰ پوند معامله می‌شود، در حالی‌که ملک مشابه در قبرس جنوبی (آیا ناپا / لارناکا) از ۱۸۰٬۰۰۰ یورو و در کوستا دل سول از ۲۰۰٬۰۰۰ یورو آغاز می‌شود. قیمت‌ها به پروژه، وضعیت تحویل، چشم‌انداز و سهم زمین بستگی دارند — برای اعداد به‌روز به آگهی‌های فعلی ما مراجعه کنید."),
    (0, 4, None,
     "درآمد اجاره کوتاه‌مدت در قبرس شمالی فصلی است. در فصل اوج (ژوئن-سپتامبر) در Long Beach ایسکله و گیرنه نرخ‌های روزانه معمولی: آپارتمان ۱+۱ معادل ۵۰-۱۰۰ پوند، ۲+۱ حدود ۸۰-۱۶۰ پوند، ویلا ۱۵۰-۴۰۰ پوند. در خارج از فصل نرخ‌ها به‌طور محسوسی کاهش می‌یابند. نرخ اشغال سالانه با مدیریت حرفه‌ای و موقعیت خوب ۶۰-۸۵٪ است. اخذ مجوز اجاره کوتاه‌مدت از شهرداری، ثبت مالیات بر ارزش افزوده و اظهارنامه سالانه مالیات بر درآمد ضروری است — چارچوب حقوقی و مالیاتی با اجاره بلندمدت متفاوت است."),

    (4, 0, None,
     "در قبرس شمالی چهار نوع اصلی سند مالکیت رایج است: "
     "۱) سند ترکی پیش از ۱۹۷۴ (Türk Malı Koçan) — املاکی که پیش از ۱۹۷۴ متعلق به قبرسی‌های ترک بوده‌اند. از نظر حقوقی قوی‌ترین و معمولاً با ارزش‌ترین نوع. "
     "۲) سند معادل (Eşdeğer) — به قبرسی‌های ترکی که از جنوب جابجا شده‌اند، در ازای ملکی که در جنوب رها کرده‌اند با سیستم امتیاز معادل اعطا شده است. تحت ضمانت دولت و رایج در بازار. "
     "۳) سند تخصیصی (Tahsis / TMD) — پس از ۱۹۷۴ توسط دولت به مهاجران ترکیه‌ای تخصیص یافته. وضعیت حقوقی بین‌المللی آن می‌تواند چالشی باشد و معمولاً برای خریداران خارجی توصیه نمی‌شود. "
     "۴) سند خارجی / سند پس از انتقال — سندهایی که قبلاً به اتباع خارجی (با موافقت شورای وزیران) انتقال داده شده‌اند؛ خریدار خارجی جدید باید فرایند موافقت را دوباره طی کند. "
     "پیش از خرید حتماً جستجوی مستقل سند (title search) توسط وکیل انجام داده و پروفایل ریسک نوع سند را ارزیابی کنید."),
    (4, 1, None,
     "برای شهروندان ترکیه که به موافقت شورای وزیران نیاز ندارند، انتقال سند معمولاً در چند روز تا ۱-۲ هفته پس از تکمیل مدارک انجام می‌شود. برای خریداران خارجی فرآیند متفاوت است: بر اساس «قانون تملک اموال غیرمنقول و اجاره طولانی‌مدت (خارجیان)» درخواست به وزارت کشور داده می‌شود، از استعلامات امنیتی پلیس و نظامی عبور می‌کند و پس از آن موافقت شورای وزیران صادر می‌شود. پس از اصلاحات ۲۰۲۳ میانگین زمان ۶-۱۲ ماه است و در دوره‌های شلوغ ممکن است طولانی‌تر شود. در این بازه، ثبت قرارداد فروش در دفتر ثبت املاک (Specific Performance) برای حفاظت از خریدار الزامی است."),
    (4, 2, None,
     "بله — قطعاً؛ برای خریدار خارجی این مهم‌ترین اقدام حقوقی در قبرس شمالی است. ثبت قرارداد فروش در دفتر ثبت املاک ظرف ۲۱ روز (پس از پرداخت حق تمبر قرارداد) حفاظت «Specific Performance» را طبق قانون قراردادها برای خریدار فراهم می‌کند: فروشنده نمی‌تواند ملک را به دیگری بفروشد، وثیقه یا حکم توقیف بر آن قرار دهد یا به‌نفع خریدار دیگری از قرارداد کنار بکشد. خریداری که قرارداد را ثبت نکند تا تحویل کامل سند، ریسک از دست دادن همه حقوق خود را دارد. حق تمبر تقریباً ۰٫۵٪ قیمت قرارداد است؛ هزینه‌های ثبت دارای بخش ثابت و بخش ارزشی است."),
    (4, 4, None,
     "بله — اگر در خارج زندگی می‌کنید می‌توانید از طریق وکالت‌نامه آپوستیل‌شده (کنوانسیون لاهه) یا مصدق کنسولگری TRNC به وکیل خود اختیار بدهید. وکالت‌نامه‌های تنظیم‌شده نزد دفتر اسناد ترکیه در TRNC معتبر است؛ وکالت‌نامه‌های کشورهای دیگر نیاز به آپوستیل (یا تصدیق کنسولگری TRNC) دارند. وکالت‌نامه باید اختیارات اعطایی را صراحتاً فهرست کند: انتقال سند، درخواست از شورای وزیران، افتتاح حساب بانکی، امضای قرارداد نزد دفتر اسناد و غیره. وکالت محدود فقط برای اقدامات لازم بر وکالت عمومی نامحدود ارجحیت دارد. هزینه کل با ترجمه معمولاً ۱۰۰-۳۰۰ پوند است."),

    (5, 0, None,
     "بله — اشخاص حقیقی خارجی می‌توانند با موافقت شورای وزیران در TRNC ملک خریداری کنند. قانون حاکم «قانون تملک اموال غیرمنقول و اجاره طولانی‌مدت (خارجیان)» (شماره ۵۲/۲۰۰۸ و اصلاحات بعدی) است. مقررات فعلی به یک شخص خارجی امکان خرید بیش از یک ملک را می‌دهد، اما مساحت مجموع و تعداد واحدها طبق قانون محدود است. از آنجا که این حدود در طول زمان (جدیدترین در ۲۰۲۳) تغییر کرده، اکیداً توصیه می‌شود پیش از خرید محدودیت‌های روز را به‌صورت مکتوب از وکیل و ما دریافت کنید. شهروندان ترکیه مشمول این روند موافقت نیستند (به سؤال بعدی مراجعه کنید)."),
    (5, 1, None,
     "موافقت شورای وزیران تأییدیه رسمی لازم برای تملک ملک توسط تبعه خارجی در TRNC است. درخواست به وزارت کشور تسلیم می‌شود و معمولاً شامل: کپی پاسپورت، مدرک آدرس، سوءپیشینه (آپوستیل‌شده از کشور مبدأ)، عکس پاسپورتی، کپی قرارداد فروش، سند و گزارش جستجوی سند، فرم‌های درخواست. گردش کار: درخواست → بررسی‌های امنیتی پلیس و نظامی → تصمیم شورای وزیران → انتقال سند پس از تأیید. میانگین زمان پس از ۲۰۲۳: ۶-۱۲ ماه. ثبت قرارداد در دفتر ثبت املاک (Specific Performance) در این دوره ضروری است. وکیل شما درخواست را تهیه و پیگیری می‌کند."),
    (5, 2, None,
     "بله — برای شهروندان ترکیه استثناهای مهمی وجود دارد. اتباع ترک مشمول روند موافقت شورای وزیران نیستند: انتقال سند مستقیماً در دفتر ثبت املاک انجام می‌شود و می‌تواند ظرف چند روز نهایی شود. معاملات با کارت شناسایی یا پاسپورت ترکیه پردازش می‌شوند. محدودیت‌های تعداد ملک و مساحت زمین که برای خارجی‌ها اعمال می‌شود به همان شکل برای اتباع ترک اعمال نمی‌شود. این امر برای آنان مزیت قابل‌توجهی از نظر فرآیند، زمان و روش حقوقی فراهم می‌آورد."),
    (5, 4, None,
     "بله — در TRNC می‌توان یک شرکت با مسئولیت محدود ثبت‌شده (Ltd.) تأسیس کرد و ملک را از طریق آن خرید؛ در موارد خاصی این کار به سرمایه‌گذاران اجازه می‌دهد محدودیت‌های افراد حقیقی خارجی را پشت سر بگذارند. تأسیس ۲-۴ هفته زمان می‌برد؛ هزینه کل (وکالت، ثبت، سرمایه شرکت) ۲٬۰۰۰-۴٬۰۰۰ پوند است. هزینه‌ها و تعهدات جاری را مد نظر داشته باشید: مالیات شرکتی بر سود فروش، ظرافت‌های مالیات بر ارزش افزوده، حسابرسی سالانه، هزینه حسابدار و گزارش درآمد اجاره. برای پرتفوی چندملکی کارآمد است؛ برای یک ملک منفرد غالباً خرید به‌عنوان شخص حقیقی مقرون‌به‌صرفه‌تر است. پیش از تصمیم، هزینه‌های کامل را با مشاور مالیاتی مدل‌سازی کنید."),

    (6, 0, None,
     "بله — مالکان خارجی املاک در TRNC می‌توانند درخواست «اقامت موقت» دهند. درخواست با مدارک زیر به وزارت کشور / اداره مهاجرت تسلیم می‌شود: پاسپورت و کپی‌ها، سند یا قرارداد فروش، گزارش بررسی پزشکی TRNC، گواهی عدم سوءپیشینه، دو عکس پاسپورتی، اثبات درآمد یا موجودی بانکی کافی و هزینه درخواست. اقامت موقت معمولاً یک‌ساله صادر می‌شود و با استمرار شرایط قابل تمدید است. چون معیارها سالانه تغییر می‌کند، الزامات به‌روز را پیش از درخواست از اداره مهاجرت یا وکیل بررسی کنید."),
    (6, 2, None,
     "شهروندی TRNC تحت شرایط خاص ممکن است اما مالکیت ملک آن را به‌طور خودکار اعطا نمی‌کند. مسیرهای اصلی: ۱) از طریق ازدواج — حداقل مدت اقامت قانونی به‌عنوان همسر شهروند TRNC پیش از تقاضا، ۲) اقامت طولانی — اقامت قانونی پیوسته به مدت سال‌های مقرر در قانون همراه با اثبات پیوند با کشور، ۳) موارد استثنایی — خدمت یا سرمایه‌گذاری خاص. این فرآیند پیچیده است و تحت قوانینی که بارها اصلاح شده‌اند شکل می‌گیرد — زمان‌های انتظار جاری، آزمون‌های زبان/فرهنگ و دیگر معیارها در طول زمان تغییر می‌کنند. پیش از اقدام، نظر مکتوب در مورد وضعیت فعلی از وکیل متخصص حقوق مهاجرت دریافت کنید."),

    (7, 0, None,
     "بازار املاک قبرس شمالی در سال‌های اخیر به‌ویژه در مناطق ساحلی رشد چشمگیری داشته — اما عملکرد گذشته ضامن بازدهی آینده نیست. بازده اجاره بلندمدت منطقی (خالص پس از هزینه‌ها) حدود ۴-۸٪ سالانه است؛ اجاره کوتاه‌مدت (تعطیلات) با مدیریت حرفه‌ای می‌تواند به ۶-۱۲٪ برسد. رشد ارزش بسته به سال و موقعیت بسیار متفاوت است. الگوهای رایج: نزدیک دانشگاه‌ها — تقاضای پایدار اجاره و رشد متعادل؛ گردشگری ساحلی (Long Beach, Bafra, Esentepe) — بازده Airbnb بالاتر اما نوسان فصلی بالا؛ مرکز گیرنه — تقاضای مستقر و مستأجران بلندمدت پایدار. برای هر سرمایه‌گذاری بررسی مستقل و مدل‌سازی جریان نقدی ضروری است."),
    (7, 2, None,
     "گزینه‌های وام مسکن در TRNC محدود است. برای شهروندان ترکیه برخی بانک‌های TRNC وام‌های مسکن تا حدود ۵۰-۷۰٪ ارزش ملک با سررسید ۵-۱۵ سال ارائه می‌کنند — نرخ‌های TL نوسان‌دار و تابع سیاست بانک مرکزی‌اند و وام ارزی محدود است. برای اتباع خارجی وام مسکن نادر است؛ اکثر خریداران خارجی نقدی پرداخت می‌کنند یا از اقساط سازنده استفاده می‌کنند. خریداران ساکن انگلستان یا اتحادیه اروپا اغلب از روش‌های equity release / remortgage در کشور خود بهره می‌برند. اقساط سازنده (در ادامه) برای بسیاری از خریداران خارجی عملی‌ترین راه تأمین مالی است."),
    (7, 4, None,
     "پروژه‌های ساحلی قبرس شمالی عمدتاً با پوند قیمت‌گذاری می‌شوند؛ برخی از یورو یا دلار استفاده می‌کنند. آگهی‌های لیر ترکیه نادرند (معمولاً ملک‌های قدیمی و برای خریداران محلی). با توجه به نوسان نرخ ارز لیر، املاک پوندی یا یورویی برای سرمایه‌گذار بلندمدت حفظ ارزش روشن‌تری ارائه می‌دهند. انتخاب ارز روی نقدشوندگی بازار نیز اثر دارد — در مناطق گردشگری ساحلی پوند غالب است، در بازار داخلی لیر رایج‌تر."),

    (8, 1, None,
     "روابط اجاره در TRNC تابع قانون کنترل اجاره و شرایط قرارداد است. حقوق اساسی مستأجر: عدم بیرون‌راندن بدون دلیل قانونی در طول مدت قرارداد، بازگرداندن کامل ودیعه در پایان قرارداد (در نبود خسارت یا بدهی)، ورود مالک تنها با اطلاع قبلی (معمولاً ۲۴ ساعت) در ساعات متعارف، افزایش سالانه اجاره در چارچوب قرارداد و نرخ‌های متعارف/قانونی، مسئولیت مالک در قبال خدمات پایه و شرایط بهداشتی، فرآیند قضایی برای دعاوی تخلیه. دادگاه‌ها یا مراجع کنترل اجاره اختلافات را حل می‌کنند. قراردادها باید دوزبانه (ترکی + انگلیسی) باشند، هر دو طرف امضا و هر صفحه پاراف کنند."),
    (8, 4, None,
     "بله — اجاره کوتاه‌مدت تعطیلاتی در TRNC قانونی و در حال رواج است. در مقیاس تجاری معمولاً نیازمند مجوز شهرداری برای اجاره کوتاه‌مدت/بهره‌برداری، اظهارنامه مالیاتی درآمد، ثبت مالیات بر ارزش افزوده و در مواردی مجوزهای وزارت گردشگری و محیط زیست است. در مجتمع‌های بسته، اساسنامه مدیریت ممکن است اجاره کوتاه‌مدت را محدود کند — پیش از خرید برنامه مدیریت را حتماً مرور کنید. میزبانان Airbnb و Booking همچنین با کمیسیون پلتفرم و تعهدات مالیات اقامت روبه‌رو هستند. شرکت‌های حرفه‌ای مدیریت اجاره تمام فرآیند (ورود/خروج، نظافت، مالیات، گزارش‌دهی) را به‌صورت بسته ارائه می‌دهند."),

    (10, 0, None,
     "مالیات‌های اصلی مرتبط با مالکیت ملک در TRNC: ۱) مالیات سالانه املاک — به شهرداری بر اساس نوع، مساحت و موقعیت پرداخت می‌شود. مبالغ به لیر ترکیه و به‌صورت دوره‌ای به‌روز می‌شوند؛ برای آپارتمان معمولاً متوسط است اما می‌تواند از چندصد تا چند هزار لیر بسته به اندازه و موقعیت متغیر باشد. نرخ‌های به‌روز را از شهرداری تأیید کنید. ۲) مالیات درآمد اجاره — از طریق اظهارنامه مالیات بر درآمد با تعرفه پلکانی. ۳) مالیات افزایش ارزش — ممکن است در فروش مجدد اعمال شود (فروشندگان حرفه‌ای/تجاری مشمول قواعد کسر متفاوتی‌اند). ۴) هزینه نگهداری مجتمع — مالیات نیست، تعهد قراردادی خصوصی است. برای برنامه‌ریزی مالیاتی از حسابدار ثبت‌شده در TRNC کمک بگیرید."),
    (10, 1, None,
     "هزینه انتقال سند عموماً حدود ۶٪ از ارزش ملک است. تخفیف‌ها و معافیت‌های قانونی در طول زمان تغییر می‌کنند: از نظر تاریخی، تخفیف خریدار بار اول (حدود ۳٪) اعمال شده و چنین سیاست‌هایی دوره‌ای اصلاح می‌شوند. به‌طور سنتی خریدار و فروشنده ۵۰-۵۰ تقسیم می‌کنند اما می‌توان با قرارداد تغییر داد. همچنین در نظر بگیرید: حق تمبر (حدود ۰٫۵٪ قیمت قرارداد)، هزینه‌های دفتر ثبت و مالیات بر ارزش افزوده ۵٪ بر خانه‌های نوساز (فروش اول). نرخ‌های روز خرید را مکتوب از دفتر ثبت یا وکیل دریافت کنید."),
    (10, 3, None,
     "هنگام فروش، اقلام هزینه زیر را در نظر بگیرید: ۱) تقسیم هزینه انتقال سند (طبق قرارداد)، ۲) کمیسیون مشاور املاک (معمولاً ۳-۵٪ + مالیات بر ارزش افزوده از فروشنده)، ۳) مالیات افزایش ارزش بر سود محقق‌شده — معافیت‌ها سالانه تغییر می‌کنند، ۴) کسر مالیات برای فروشندگان حرفه‌ای (سازنده‌ها، معامله‌گران مکرر)، ۵) هزینه وکالت، ۶) هزینه تسویه زودهنگام وام در صورت وجود. نکته مهم: اعلام قیمت کمتر در قرارداد (عرف در کشورهای دیگر) در TRNC غیرقانونی است، ریسک جدی کیفری/حقوقی برای هر دو طرف ایجاد می‌کند و می‌تواند ثبت سند را باطل سازد. Nexos همواره معاملات شفاف به قیمت واقعی را توصیه می‌کند."),

    (13, 0, None,
     "خدمات درمانی در TRNC توسط هر دو بخش دولتی و خصوصی ارائه می‌شود. بیمارستان‌های دولتی اصلی: بیمارستان دولتی دکتر برهان نالبانت‌اوغلو در نیکوزیا (بزرگ‌ترین)، بیمارستان دولتی فاماگوستا، بیمارستان دولتی دکتر آکچیچک در گیرنه. ارائه‌دهندگان خصوصی پیشرو: Near East Hospital (NEU، نیکوزیا)، Kolan British Hospital (نیکوزیا)، بیمارستان دانشگاه گیرنه و Hayat Hospital در گیرنه — با تجهیزات پیشرفته، اغلب با اعتبار بین‌المللی و خدمات انگلیسی‌زبان. اتباع خارجی می‌توانند از خدمات اورژانس بیمارستان‌های دولتی استفاده کنند؛ بیمه سلامت خصوصی برای درمان جامع قویاً توصیه می‌شود (معمولاً ۴۰۰-۱٬۲۰۰ پوند در سال). کارت EHIC اتحادیه اروپا در TRNC معتبر نیست."),
    (13, 2, None,
     "شماره‌های اصلی اضطراری: ۱۱۲ (اورژانس مرکزی / آمبولانس)، ۱۵۵ (پلیس)، ۱۹۹ (آتش‌نشانی). بیمارستان‌های خصوصی خطوط اضطراری ۲۴ ساعته خود را دارند. در موارد تخصصی یا بحرانی، انتقال با آمبولانس هوایی به ترکیه (عمدتاً آنکارا، استانبول، آدانا) امکان‌پذیر است و اغلب تحت پوشش بیمه‌های خصوصی جامع قرار می‌گیرد. Nexos به مالکان خدمات پشتیبانی واتساپ ۲۴/۷، اطلاعات تماس بیمارستان‌ها و پزشکان شریک و هماهنگی خدمات آمبولانس ارائه می‌دهد."),

    (3, 2, None,
     "هزینه‌های متداول خرید در TRNC: ۱) هزینه انتقال سند — حدود ۶٪ از ارزش ملک (تخفیف خریدار بار اول ممکن است در تاریخ‌های معین اعمال شود؛ با دفتر ثبت تأیید کنید). به‌طور سنتی ۵۰-۵۰ بین خریدار و فروشنده، اما با قرارداد قابل تغییر. ۲) مالیات بر ارزش افزوده — ۵٪ بر خانه‌های نوساز (فروش اول)؛ عموماً به زمین یا فروش دست دوم اعمال نمی‌شود. ۳) حق تمبر — حدود ۰٫۵٪ قیمت قرارداد (هنگام ثبت در دفتر ثبت). ۴) هزینه وکالت — معمولاً ۱-۱٫۵٪ ارزش (از حدود ۱٬۰۰۰ پوند شروع). ۵) کمیسیون مشاور املاک — معمولاً از فروشنده (۳-۵٪ + مالیات بر ارزش افزوده)؛ گاه از خریدار. ۶) هزینه‌های ثبت و اداری دفتر ثبت. ۷) هزینه‌های درخواست شورای وزیران (برای خریداران خارجی). هزینه‌های اضافی را روی‌هم تقریباً ۸-۱۲٪ از ارزش ملک برنامه‌ریزی کنید."),
]

FA_NEW = [
    (1, {
        "question": "ریسک زلزله چه اندازه است؟ برای ایمنی سازه به چه مواردی دقت کنیم؟",
        "answer": "TRNC نزدیک به کمربند لرزه‌ای شرق مدیترانه قرار دارد اما در ناحیه پرخطری مانند گسل‌های شمال-جنوب ترکیه نیست. در سال‌های اخیر چند زلزله محسوس بدون خسارت قابل توجه رخ داده است. با این حال ایمنی لرزه‌ای باید اولویت انتخاب ملک باشد: ۱) بافت جدیدتر (۱۰-۱۵ سال اخیر) که با آیین‌نامه ساختمانی جاری TRNC ساخته شده ارجح است. ۲) مدارک طراحی سازه و مجوز ساخت را درخواست کنید و گزارش نظارت را مرور کنید. ۳) از مهندس یا ارزیاب مستقل بخواهید پارامترهای کلیدی — رده بتن (ترجیحاً C30 یا بالاتر)، کیفیت میلگرد، نسبت دیوار برشی — را بررسی کند. ۴) بیمه زلزله قانوناً اجباری نیست اما اکیداً توصیه می‌شود (حدود ۱۰۰-۲۵۰ پوند در سال)."
    }),
    (3, {
        "question": "پس از خرید، آب، برق و اینترنت چگونه وصل می‌شود؟",
        "answer": "اتصال امکانات معمولاً پس از انتقال سند چنین پیش می‌رود: ۱) برق (KIB-TEK) — مراجعه به دفتر محلی KIB-TEK با سند، کارت شناسایی و اثبات سکونت؛ ودیعه حدود ۱۰۰-۳۰۰ پوند بسته به اندازه، و تسویه قبوض مالک قبلی پیش‌نیاز است. ۲) آب — درخواست در شهرداری؛ هزینه‌ها و ودیعه به شهر بستگی دارد. در برخی مجتمع‌ها آب از سیستم مشترک توزیع می‌شود و با مدیریت مجموعه هماهنگ می‌شود. ۳) اینترنت — ارائه‌دهندگان اصلی Telsim، Turkcell KKTC و Primetel هستند. فیبر در بیشتر مراکز شهر و مجتمع‌های ساحلی موجود است؛ بسته‌ها ماهانه ۲۵-۸۰ پوند. نصب ۳-۷ روز کاری. Nexos کل اتصال‌ها را با وکالت انجام می‌دهد و برای مالکان غیرمقیم مدیریت قبوض ارائه می‌کند."
    }),
    (5, {
        "question": "چگونه و از چه کانال‌هایی بهای خرید را به TRNC منتقل کنم؟",
        "answer": "کنترل ارزی TRNC نسبتاً انعطاف‌پذیر است اما هر پرداخت باید از طریق بانک و مستند (با ارجاع به قرارداد فروش) انجام شود. روش‌های رایج: ۱) حواله سوئیفت بین‌المللی — مستقیماً به حساب بانکی فروشنده در TRNC؛ برای مبالغ بالا ممکن است مستندات (قرارداد و توجیه) درخواست شود. ۲) افتتاح حساب بانکی TRNC به نام خودتان و پرداخت از آنجا — راه ترجیحی و کاملاً قابل ردیابی؛ برای افتتاح پاسپورت، آدرس و معرفی‌نامه کافی است (۱-۵ روز کاری). ۳) حساب امانی (Escrow) — گزینه امن‌تر که وجوه در حساب مشتری وکیل تا احراز شرایط نگه داشته می‌شود. ۴) Wise / Transferwise و خدمات مشابه فین‌تک — به‌صرفه برای مبالغ کوچک و متوسط. نکته مهم: پرداخت‌های نقدی بزرگ نگرانی‌های مبارزه با پولشویی ایجاد می‌کنند؛ همواره از مسیرهای بانکی استفاده کنید و رسیدهای بانکی را همراه قرارداد نگه دارید. همچنین سقف ارز خروجی و ضوابط مالیاتی کشور مبدأ را بررسی کنید."
    }),
]

# ---------------------------------------------------------------------------
# Apply
# ---------------------------------------------------------------------------

def apply(locale, patches, new_items):
    path = MSG / locale / "sss.json"
    with path.open("r", encoding="utf-8") as f:
        d = json.load(f)
    cats = d["sss"]["categories"]
    for (ci, ii, nq, na) in patches:
        if nq is not None:
            cats[ci]["items"][ii]["question"] = nq
        cats[ci]["items"][ii]["answer"] = na
    for (ci, new) in new_items:
        cats[ci]["items"].append(new)
    with path.open("w", encoding="utf-8") as f:
        json.dump(d, f, ensure_ascii=False, indent=2)
    total = sum(len(c["items"]) for c in cats)
    print(f"{locale}: patched {len(patches)}, appended {len(new_items)} → {total} Q&A")

apply("en", EN_PATCHES, EN_NEW)
apply("de", DE_PATCHES, DE_NEW)
apply("ru", RU_PATCHES, RU_NEW)
apply("fa", FA_PATCHES, FA_NEW)
