-- 026: Seed additional settings for comprehensive settings page
INSERT INTO site_settings (key, value, value_type, label, category) VALUES
  ('site_title', 'Nexos Investment', 'string', 'Site Başlığı', 'general'),
  ('site_description', 'Kuzey Kıbrıs gayrimenkul danışmanlığı', 'string', 'Site Açıklaması', 'general'),
  ('primary_color', '#ffca3e', 'color', 'Ana Renk', 'general'),
  ('google_maps_link', 'https://maps.app.goo.gl/jUajHgW2DWPzDKfJA', 'url', 'Google Maps Linki', 'general'),
  ('meta_title_template', '%s | Nexos Investment', 'string', 'Meta Başlık Şablonu', 'seo'),
  ('default_meta_description', 'Kuzey Kıbrıs''ta güvenilir gayrimenkul danışmanlığı', 'string', 'Varsayılan Meta Açıklama', 'seo'),
  ('google_analytics_id', '', 'string', 'Google Analytics ID', 'seo'),
  ('search_console_verification', '', 'string', 'Search Console Doğrulama', 'seo'),
  ('whatsapp_number', '+905488604030', 'string', 'WhatsApp Numarası', 'contact'),
  ('working_hours_weekdays', '09:00-18:00', 'string', 'Hafta İçi', 'contact'),
  ('working_hours_saturday', '09:00-14:00', 'string', 'Cumartesi', 'contact'),
  ('working_hours_sunday', 'Kapalı', 'string', 'Pazar', 'contact'),
  ('office_lat', '35.160', 'string', 'Ofis Enlem', 'contact'),
  ('office_lng', '33.880', 'string', 'Ofis Boylam', 'contact'),
  ('social_facebook', 'https://www.facebook.com/nexosinvestment', 'url', 'Facebook', 'social'),
  ('social_instagram', 'https://www.instagram.com/nexosinvestment', 'url', 'Instagram', 'social'),
  ('social_youtube', 'https://www.youtube.com/@nexosinvestment', 'url', 'YouTube', 'social'),
  ('social_tiktok', 'https://www.tiktok.com/@nexosinvestment', 'url', 'TikTok', 'social'),
  ('default_hashtags', 'KuzeyKıbrıs,KKTC,NexosInvestment,Emlak', 'string', 'Varsayılan Hashtagler', 'social'),
  ('notification_email', 'info@nexosinvestment.com', 'string', 'Bildirim E-postası', 'email'),
  ('theme_default', 'system', 'string', 'Varsayılan Tema', 'appearance'),
  ('homepage_deals_visible', 'true', 'boolean', 'Fırsat İlanlar', 'appearance'),
  ('homepage_featured_visible', 'true', 'boolean', 'Vitrin', 'appearance'),
  ('homepage_blog_visible', 'true', 'boolean', 'Blog', 'appearance'),
  ('homepage_video_visible', 'true', 'boolean', 'Video', 'appearance'),
  ('homepage_slider_visible', 'true', 'boolean', 'Slider', 'appearance'),
  ('notify_new_contact', 'true', 'boolean', 'Yeni İletişim', 'notifications'),
  ('notify_new_offer', 'true', 'boolean', 'Yeni Teklif', 'notifications'),
  ('notify_property_expiry', 'true', 'boolean', 'İlan Süresi Dolma', 'notifications')
ON CONFLICT (key) DO NOTHING;
